# Generated by Django 5.2.15 on 2026-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('VILLA', 'Villa'), ('APARTMENT', 'Apartment')], default='VILLA', max_length=20),
        ),
    ]
